version: "3.7"
volumes:
  datastore-develop:
services:
  database-test:
    platform: linux/amd64
    image: mysql:8.0.28
    ports: [3306:3306]
    healthcheck:
      test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'SHOW DATABASES;'
      interval: 2s
      timeout: 2s
      retries: 25
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
